# Generated by Django 5.1.1 on 2024-11-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_company_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcompanyinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newcompanyinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
    ]
