# Generated by Django 5.1.1 on 2024-11-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
