# Generated by Django 5.1.1 on 2024-11-22 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_restaurant_id_alter_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant_id',
        ),
    ]
