# Generated by Django 5.1.1 on 2024-11-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_city_order_complement_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street',
        ),
    ]
