# Generated by Django 5.1.1 on 2024-10-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resetpassword', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
